routes/web.php
<?php

use App\Http\Controllers\Frontsite\HomeController;

use App\Http\Controllers\Frontsite\Profile\JobWishlistController;
use App\Http\Controllers\Frontsite\Profile\ProfilesController;
use App\Http\Controllers\Frontsite\Profile\UserExperienceController;
use App\Http\Controllers\Frontsite\Profile\UserEducationController;
use App\Http\Controllers\Frontsite\Profile\UserSkillController;
use App\Http\Controllers\Frontsite\Profile\UserResumeController;
use App\Http\Controllers\Frontsite\Profile\UserSecurityController;

use App\Http\Controllers\Frontsite\Operational\ApplicantController;
use App\Http\Controllers\Frontsite\Operational\CompanyController;
use App\Http\Controllers\Frontsite\Operational\JobVacancyController;

use App\Http\Controllers\Frontsite\Content\AnnouncementController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontsite ------------------------------- //

    // home ------------------------------- //
    Route::get('/', [HomeController::class, 'index'])->name('home');
    // end home ------------------------------- //
    
    
    // operational ------------------------------- //
        // job vacancy
        Route::get('job_vacancy/filter', [JobVacancyController::class, 'filter'])->name('job-vacancy.filter');
        Route::resource('job_vacancy', JobVacancyController::class);
        // company
        Route::resource('company', CompanyController::class);
    // end operational ------------------------------- //


    // content ------------------------------- //
        // announcement
        Route::resource('announcement', AnnouncementController::class);
    // end content ------------------------------- //
    

Route::group(['middleware' => ['auth:sanctum']], function () {
    
    // profile ------------------------------- //
        // personal info
        Route::get('select/regency/profile/{id}', [ProfilesController::class, 'select_regency_profile'])->name('select_regency.profile');
        Route::get('select/district/profile/{id}', [ProfilesController::class, 'select_district_profile'])->name('select_district.profile');
        Route::put('upload/photo/profile/{id}', [ProfilesController::class, 'upload'])->name('upload.photo.profile');
        Route::get('reset/photo/profile/{id}', [ProfilesController::class, 'reset'])->name('reset.photo.profile');
        Route::resource('profile', ProfilesController::class)->except('show');
        // Security
        Route::get('security/profile', [UserSecurityController::class, 'security'])->name('security.profile');
        Route::put('update/email/security/profile', [UserSecurityController::class, 'update_email'])->name('update.email.security.profile');
        Route::put('update/password/security/profile', [UserSecurityController::class, 'update_password'])->name('update.password.security.profile');
        Route::resource('security', UserSecurityController::class);
        // work experience
        Route::get('work_experience/profile', [UserExperienceController::class, 'work_experience'])->name('work_experience.profile');
        Route::resource('work_experience', UserExperienceController::class);
        // education
        Route::get('education/profile', [UserEducationController::class, 'education'])->name('education.profile');
        Route::resource('education', UserEducationController::class);
        // skill
        Route::get('reset/skill/profile', [UserSkillController::class, 'reset'])->name('reset.skill.profile');
        Route::get('skill/profile', [UserSkillController::class, 'skill'])->name('skill.profile');
        Route::resource('skill', UserSkillController::class);
        // resume
        Route::get('resume/profile', [UserResumeController::class, 'resume'])->name('resume.profile');
        Route::resource('resume', UserResumeController::class);
        // job wishlist
        Route::get('job_wishlist/profile', [JobWishlistController::class, 'wishlist'])->name('job_wishlist.profile');
        Route::resource('job_wishlist', JobWishlistController::class);
    // end profile ------------------------------- //


    // operational ------------------------------- //
        // my application
        Route::get('my_application/filter', [ApplicantController::class, 'filter'])->name('applicant.filter');
        Route::get('my_application', [ApplicantController::class, 'my_application'])->name('applicant.my_application');
        // apply job
        Route::resource('applicant', ApplicantController::class)->middleware('verified');
    // end operational ------------------------------- //

});
    
// end frontsite ------------------------------- //

app/Http/Controllers/Frontsite/Content/AnnouncementController.php
<?php

namespace App\Http\Controllers\Frontsite\Content;

use App\Http\Controllers\Controller;

use App\Models\Content\Announcement;
use App\Models\Operational\Applicant;
use App\Models\Operational\JobVacancy;

use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // group by announcements
        $announcement = Announcement::with(['company.user','position',])
                                    ->whereDate('start_date', '<=', date('Y-m-d H:i:s'))
                                    ->whereDate('end_date', '>=', date('Y-m-d H:i:s'))
                                    ->orderBy('created_at', 'desc')
                                    ->paginate(10);

        return view('pages.frontsite.content.announcment.index', compact('announcement'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $announcement = Announcement::where('slug', $slug)->firstOrFail();
        
        $job_vacancy = JobVacancy::where('company_id', $announcement->company_id)
                                    ->where('position_id', $announcement->position_id)
                                    ->firstOrFail();
        
        $applicant = Applicant::with(['user', 'job_vacancy.position','job_vacancy.company.user'])
                                ->where('job_vacancy_id', $job_vacancy->id)
                                ->where('step', $announcement->status_recruitment)
                                ->paginate(500);
                        
        return view('pages.frontsite.content.announcment.show', compact('applicant', 'announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

app/Http/Controllers/Frontsite/HomeController.php
<?php

namespace App\Http\Controllers\Frontsite;

use App\Http\Controllers\Controller;
use App\Models\MasterData\CompanyContractHistory;
use App\Models\MasterData\JobType;
use App\Models\MasterData\LevelOfEducation;
use App\Models\MasterData\Provinces;
use App\Models\Operational\JobVacancy;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $job_vacancy = JobVacancy::with(['company.user', 'position', 'provinces'])
                        ->whereHas('company', function($query) {
                            $query->where('status', 1);
                        })
                        ->whereHas('company.company_contract_history', function($query) {
                            $query->whereHas('company_contract', function($query) {
                                $query->where('status', 1)
                                        ->whereDate('end_period', '>=', date('Y-m-d'));
                            });
                        })
                        ->inRandomOrder()
                        ->where(function($query) {
                            $query->where('status', 1)
                                ->whereDate('start_date', '<=', date('Y-m-d'))
                                ->whereDate('end_date', '>=', date('Y-m-d'));
                            })
                        ->paginate(30);
                        
        $province = Provinces::all()->pluck('name', 'id');
        $job_type = JobType::all()->pluck('name', 'id');
        $level_of_education = LevelOfEducation::all()->pluck('name', 'id');

        return view('pages.frontsite.home-page.index', compact('job_vacancy', 'province', 'job_type', 'level_of_education'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

app/Http/Controllers/Frontsite/Operational/ApplicantController.php
<?php

namespace App\Http\Controllers\Frontsite\Operational;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Operational\ApplyJobRequest;

use App\Models\Operational\Applicant;

use Illuminate\Http\Request;

class ApplicantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ApplyJobRequest $request)
    {
        $data = $request->all();

        $data['users_id'] = auth()->user()->id;

        $data['step'] = 1;

        Applicant::create($data);

        alert()->success('Pesan Sukses', 'Permohonan Anda telah dikirim');
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $my_application = Applicant::with(['job_vacancy.company.user', 'job_vacancy.position'])->findOrFail($id);

        return view('pages.frontsite.operational.application.show', compact('my_application'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }

    // custom function
    public function my_application()
    {
        $user = auth()->user();
        $my_application = Applicant::with(['job_vacancy.company.user', 'job_vacancy.position'])->latest()->where('users_id', $user->id)->paginate(500);

        return view('pages.frontsite.operational.application.index', compact('my_application'));
    }

    public function filter(Request $request, Applicant $applicant)
    {
        $data = $request->all();

        $user = auth()->user();

        // query builder 
        $applicant_query = $applicant->newQuery();

        if (isset($data['step'])) {
            $applicant_query->where('step', $data['step']);
        }

        $my_application = $applicant_query->with(['job_vacancy.company.user', 'job_vacancy.position'])
                                        ->latest()
                                        ->where('users_id', $user->id)
                                        ->paginate(500);


        return view('pages.frontsite.operational.application.index', compact('my_application'));
    }
}

app/Http/Controllers/Frontsite/Operational/CompanyController.php
<?php

namespace App\Http\Controllers\Frontsite\Operational;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Operational\StoreCompanyRequest;
use App\Http\Requests\Frontsite\Profile\StoreAccountRequest;

use App\Models\MasterData\Company;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.frontsite.operational.company.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAccountRequest $request, StoreCompanyRequest $request_company)
    {
        $data_user = $request->all();

        // set user type
        $data_user['user_type_id'] = 2;

        // set hash password
        $data_user['password'] = Hash::make($data_user['password']);

        // create user
        $user = User::create($data_user);

        // sync role by users select
        $user->role()->sync(4);

        $data_company = $request_company->all();

        // set user id
        $data_company['users_id'] = $user->id;

        // set mobile phone
        if ($request->filled('contact')) {
            $data_company['contact'] = str_replace('+', '', $data_company['contact']);
            $data_company['contact'] = str_replace(' ', '', $data_company['contact']);
            $data_company['contact'] = str_replace('_', '', $data_company['contact']);
        }

        Company::create($data_company);

        return redirect()->back()->with('success', 'Silahkan cek email anda untuk update informasi akun anda.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

resources/views/pages/frontsite/home-page/index.blade.php
@extends('layouts.default')
    
{{-- set content --}}
@section('content')
<!-- ========== MAIN CONTENT ========== -->
  <main id="content" role="main">
    <form method="GET" action="{{ route('job-vacancy.filter') }}">
      <!-- Hero -->
      <div class="gradient-x-three-sm-primary">
        <div class="container content-space-2">
            <!-- Input Card -->
            <div class="input-card input-card-sm mb-3">
              <div class="input-card-form">
                <label for="keyword" class="form-label visually-hidden">Pekerjaan, kata kunci atau perusahaan</label>
                <div class="input-group input-group-merge">
                  <span class="input-group-prepend input-group-text">
                    <i class="bi-search"></i>
                  </span>
                  <input type="text" class="form-control" name="keyword" id="keyword" value="{{ request('keyword') ?? '' }}" placeholder="Pekerjaan, kata kunci atau perusahaan" aria-label="Pekerjaan, kata kunci atau perusahaan" minlength="3" autocomplete="off" required>
                </div>
              </div>
  
              <div class="input-card-form">
                <label for="cityForm" class="form-label visually-hidden">Lokasi</label>
               
                <div class="input-group input-group-merge" style="overflow: visible">
                  <span class="input-group-prepend input-group-text">
                    <i class="bi-geo-alt"></i>
                  </span>
                  <!-- Select -->
                  <div class="tom-select-custom w-100">
                    <select class="js-select form-select" name="province_id" autocomplete="off"
                            data-hs-tom-select-options='{
                              "width": "100%",
                              "dropdownLeft": true,
                              "searchInDropdown": false,
                              "hidePlaceholderOnSearch": true,
                              "placeholder": "Pilih Lokasi..."
                            }'>
                      <option value="">Pilih Lokasi...</option>
                      @foreach ($province as $id => $name)
                        <option value="{{ $id }}" {{ request('province_id') == $id ? 'selected' : '' }}>{{ $name }}</option>
                      @endforeach
  
                    </select>
                  </div>
                  <!-- End Select -->
                </div>
              </div>
  
              <button type="submit" class="btn btn-gold">Search</button>
  
              @if(request('keyword') || request('province_id') || request('level_of_education_id') || request('job_type_id'))
                <a href="{{ route('home') }}" class="btn btn-outline-seconday">
                    Reset
                </a>   
              @endif
            </div>
            <!-- End Input Card -->
  
          {{-- <div class="row align-items-center">
            <div class="col-md-auto mb-3 mb-lg-0">
              <h6 class="mb-1">Limit search to:</h6>
            </div>
            <!-- End Col -->
  
            <div class="col-md mb-3 mb-lg-0">
              <!-- Check -->
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="jobSearchToCheckbox1" value="option1" checked>
                <label class="form-check-label" for="jobSearchToCheckbox1">Job title</label>
              </div>
              <!-- End Check -->
  
              <!-- Check -->
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="jobSearchToCheckbox2" value="option2">
                <label class="form-check-label" for="jobSearchToCheckbox2">Skills</label>
              </div>
              <!-- End Check -->
  
              <!-- Check -->
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="jobSearchToCheckbox3" value="option3">
                <label class="form-check-label" for="jobSearchToCheckbox3">Companies</label>
              </div>
              <!-- End Check -->
  
              <!-- Check -->
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="jobSearchToCheckbox4" value="option4">
                <label class="form-check-label" for="jobSearchToCheckbox4">Field of study</label>
              </div>
              <!-- End Check -->
            </div>
  
            <div class="col-md-auto">
              <!-- Switch -->
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="remoteOnlySwitch">
                <label class="form-check-label" for="remoteOnlySwitch">Remote only</label>
              </div>
              <!-- End Switch -->
            </div>
            <!-- End Col -->
          </div> --}}
          <!-- End Row -->
        </div>
      </div>
      <!-- End Hero -->

      <!-- Card Grid -->
      <div class="container content-space-t-1 content-space-t-md-2 content-space-b-2 content-space-b-lg-3">
        <div class="row">

          <div class="col-lg-12">
            <div class="row align-items-center mb-5">
              <div class="col-sm-6 mb-3 mb-sm-0">
                <h3 class="mb-0">
                  @if ($job_vacancy->total() > 0)
                    Page {{ number_format($job_vacancy->currentPage()) }} - {{ number_format($job_vacancy->lastPage()) }} dari {{ number_format($job_vacancy->total()) }} lowongan
                  @else
                    Tidak ada lowongan yang ditemukan
                  @endif
                </h3>
              </div>

              <div class="col-sm-6">
                <div class="d-sm-flex justify-content-sm-end align-items-center">
                  <!-- Select -->
                  <div class="mb-2 mb-sm-0 me-sm-2 flex-fill">
                    <div class="tom-select-custom">
                      <select class="js-select form-select" autocomplete="off"
                              name="level_of_education_id" onchange="this.form.submit()"
                              data-hs-tom-select-options='{
                                "searchInDropdown": false,
                                "hidePlaceholderOnSearch": true,
                                "placeholder": "Kualifikasi Pendidikan"
                              }'>
                        <option value="">Kualifikasi Pendidikan</option>
                        @foreach ($level_of_education as $id => $name)
                          <option value="{{ $id }}" {{ request('level_of_education_id') == $id ? 'selected' : '' }}>{{ $name }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <!-- End Select -->

                  <!-- Select -->
                  <div class="mb-2 mb-sm-0 me-sm-2 flex-fill">
                      <div class="tom-select-custom">
                      <select class="js-select form-select" autocomplete="off"
                              name="job_type_id" onchange="this.form.submit()"
                              data-hs-tom-select-options='{
                                "searchInDropdown": false,
                                "hidePlaceholderOnSearch": true,
                                "placeholder": "Tipe Pekerjaan"
                              }'>
                        <option value="">Tipe Pekerjaan</option>
                        @foreach ($job_type as $id => $name)
                          <option value="{{ $id }}" {{ request('job_type_id') == $id ? 'selected' : '' }}>{{ $name }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <!-- End Select -->
                </div>
              </div>
            </div>
            <!-- End Row -->

            <div class="row row-cols-1 row-cols-sm-2 mb-5">

              @forelse ($job_vacancy as $job_vacancy_item)
                  <div class="col mb-5">
                    <!-- Card -->
                    <a class="card card-bordered card-transition h-100" href="{{ route('job_vacancy.show', $job_vacancy_item->uuid) }}" target="_blank" rel="noopener noreferrer">
                      <!-- Card Body -->
                      <div class="card-body">
                        <div class="row mb-3">
                          <div class="col">
                            <!-- Media -->
                            <div class="d-flex align-items-center">
                              <div class="flex-shrink-0">
                                <img src="
                                  @if ($job_vacancy_item->company->image != "")
                                      {{ $job_vacancy_item->company->image_url }}
                                  @else
                                      {{ asset('/back-design/clients/default/image-not-found.svg') }}
                                  @endif "
                                  alt="{{ $job_vacancy_item->company->user->name ?? 'job vacancy logo' }}" class="avatar avatar-sm avatar-4x3">
                              </div>

                              <div class="flex-grow-1 ms-3">
                                <h6 class="card-title">
                                  <span class="text-dark">{{ isset($job_vacancy_item->company->user->name) ? Str::title($job_vacancy_item->company->user->name)  : '' }}</span>
                                </h6>
                              </div>
                            </div>
                            <!-- End Media -->
                          </div>
                          <!-- End Col -->
                        </div>
                        <!-- End Row -->

                        <h3 class="card-title text-inherit">
                          <span class="text-dark">{{ isset($job_vacancy_item->position->name) ? Str::title($job_vacancy_item->position->name) : '' }}</span>
                        </h3>

                      </div>
                      <!-- End Card Body -->

                      <!-- Card Footer -->
                      <div class="card-footer pt-0">
                        <ul class="list-inline list-separator small text-body">
                          <li class="list-inline-item"><i class="bi bi-briefcase-fill pe-2"></i> {{ isset($job_vacancy_item->experience_year) ? 'Min ' . $job_vacancy_item->experience_year . ' tahun' : 'Tidak ada' }}</li>
                          <li class="list-inline-item"><i class="bi bi-geo-alt-fill pe-2"></i> {{ $job_vacancy_item->provinces->name ?? '' }}</li>
                          <li class="list-inline-item"><i class="bi bi-clock-fill pe-2"></i> Posted {{ $job_vacancy_item->created_at->diffForHumans() }}</li>
                        </ul>
                      </div>
                      <!-- End Card Footer -->
                    </a>
                    <!-- End Card -->
                  </div>
                  <!-- End Col -->
              @empty
                  <!-- Content -->
                  <div class="container col my-5 text-center">
                    <div class="mb-3">
                      <img class="img-fluid" src="{{ asset('front-design/assets/img/illustrations/sorry.png') }}" alt="Image Description" style="width: 18rem;">
                    </div>

                    <div class="mb-4">
                      <h2 class="my-2">Oops!</h2>
                      <p class="fs-4">Lowongan pekerjaan tidak ditemukan.</p>
                    </div>
                  </div>
              @endforelse

            </div>
            <!-- End Row -->

            <!-- Pagination -->
            {{ $job_vacancy->links('pagination::bootstrap-4') }}
            <!-- End Pagination -->
          </div>
          <!-- End Col -->

        </div>
        <!-- End Row -->
      </div>
      <!-- End Card Grid -->
    </form>
  </main>
<!-- ========== END MAIN CONTENT ========== -->
@endsection