routes/web.php
<?php

use App\Http\Controllers\Frontsite\HomeController;

use App\Http\Controllers\Frontsite\Profile\JobWishlistController;
use App\Http\Controllers\Frontsite\Profile\ProfilesController;
use App\Http\Controllers\Frontsite\Profile\UserExperienceController;
use App\Http\Controllers\Frontsite\Profile\UserEducationController;
use App\Http\Controllers\Frontsite\Profile\UserSkillController;
use App\Http\Controllers\Frontsite\Profile\UserResumeController;
use App\Http\Controllers\Frontsite\Profile\UserSecurityController;

use App\Http\Controllers\Frontsite\Operational\ApplicantController;
use App\Http\Controllers\Frontsite\Operational\CompanyController;
use App\Http\Controllers\Frontsite\Operational\JobVacancyController;

use App\Http\Controllers\Frontsite\Content\AnnouncementController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontsite ------------------------------- //

    // home ------------------------------- //
    Route::get('/', [HomeController::class, 'index'])->name('home');
    // end home ------------------------------- //
    
    
    // operational ------------------------------- //
        // job vacancy
        Route::get('job_vacancy/filter', [JobVacancyController::class, 'filter'])->name('job-vacancy.filter');
        Route::resource('job_vacancy', JobVacancyController::class);
        // company
        Route::resource('company', CompanyController::class);
    // end operational ------------------------------- //


    // content ------------------------------- //
        // announcement
        Route::resource('announcement', AnnouncementController::class);
    // end content ------------------------------- //
    

Route::group(['middleware' => ['auth:sanctum']], function () {
    
    // profile ------------------------------- //
        // personal info
        Route::get('select/regency/profile/{id}', [ProfilesController::class, 'select_regency_profile'])->name('select_regency.profile');
        Route::get('select/district/profile/{id}', [ProfilesController::class, 'select_district_profile'])->name('select_district.profile');
        Route::put('upload/photo/profile/{id}', [ProfilesController::class, 'upload'])->name('upload.photo.profile');
        Route::get('reset/photo/profile/{id}', [ProfilesController::class, 'reset'])->name('reset.photo.profile');
        Route::resource('profile', ProfilesController::class)->except('show');
        // Security
        Route::get('security/profile', [UserSecurityController::class, 'security'])->name('security.profile');
        Route::put('update/email/security/profile', [UserSecurityController::class, 'update_email'])->name('update.email.security.profile');
        Route::put('update/password/security/profile', [UserSecurityController::class, 'update_password'])->name('update.password.security.profile');
        Route::resource('security', UserSecurityController::class);
        // work experience
        Route::get('work_experience/profile', [UserExperienceController::class, 'work_experience'])->name('work_experience.profile');
        Route::resource('work_experience', UserExperienceController::class);
        // education
        Route::get('education/profile', [UserEducationController::class, 'education'])->name('education.profile');
        Route::resource('education', UserEducationController::class);
        // skill
        Route::get('reset/skill/profile', [UserSkillController::class, 'reset'])->name('reset.skill.profile');
        Route::get('skill/profile', [UserSkillController::class, 'skill'])->name('skill.profile');
        Route::resource('skill', UserSkillController::class);
        // resume
        Route::get('resume/profile', [UserResumeController::class, 'resume'])->name('resume.profile');
        Route::resource('resume', UserResumeController::class);
        // job wishlist
        Route::get('job_wishlist/profile', [JobWishlistController::class, 'wishlist'])->name('job_wishlist.profile');
        Route::resource('job_wishlist', JobWishlistController::class);
    // end profile ------------------------------- //


    // operational ------------------------------- //
        // my application
        Route::get('my_application/filter', [ApplicantController::class, 'filter'])->name('applicant.filter');
        Route::get('my_application', [ApplicantController::class, 'my_application'])->name('applicant.my_application');
        // apply job
        Route::resource('applicant', ApplicantController::class)->middleware('verified');
    // end operational ------------------------------- //

});
    
// end frontsite ------------------------------- //

app/Http/Controllers/Frontsite/Content/AnnouncementController.php
<?php

namespace App\Http\Controllers\Frontsite\Content;

use App\Http\Controllers\Controller;

use App\Models\Content\Announcement;
use App\Models\Operational\Applicant;
use App\Models\Operational\JobVacancy;

use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // group by announcements
        $announcement = Announcement::with(['company.user','position',])
                                    ->whereDate('start_date', '<=', date('Y-m-d H:i:s'))
                                    ->whereDate('end_date', '>=', date('Y-m-d H:i:s'))
                                    ->orderBy('created_at', 'desc')
                                    ->paginate(10);

        return view('pages.frontsite.content.announcment.index', compact('announcement'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $announcement = Announcement::where('slug', $slug)->firstOrFail();
        
        $job_vacancy = JobVacancy::where('company_id', $announcement->company_id)
                                    ->where('position_id', $announcement->position_id)
                                    ->firstOrFail();
        
        $applicant = Applicant::with(['user', 'job_vacancy.position','job_vacancy.company.user'])
                                ->where('job_vacancy_id', $job_vacancy->id)
                                ->where('step', $announcement->status_recruitment)
                                ->paginate(500);
                        
        return view('pages.frontsite.content.announcment.show', compact('applicant', 'announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

app/Http/Controllers/Frontsite/HomeController.php
<?php

namespace App\Http\Controllers\Frontsite;

use App\Http\Controllers\Controller;
use App\Models\MasterData\CompanyContractHistory;
use App\Models\MasterData\JobType;
use App\Models\MasterData\LevelOfEducation;
use App\Models\MasterData\Provinces;
use App\Models\Operational\JobVacancy;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $job_vacancy = JobVacancy::with(['company.user', 'position', 'provinces'])
                        ->whereHas('company', function($query) {
                            $query->where('status', 1);
                        })
                        ->whereHas('company.company_contract_history', function($query) {
                            $query->whereHas('company_contract', function($query) {
                                $query->where('status', 1)
                                        ->whereDate('end_period', '>=', date('Y-m-d'));
                            });
                        })
                        ->inRandomOrder()
                        ->where(function($query) {
                            $query->where('status', 1)
                                ->whereDate('start_date', '<=', date('Y-m-d'))
                                ->whereDate('end_date', '>=', date('Y-m-d'));
                            })
                        ->paginate(30);
                        
        $province = Provinces::all()->pluck('name', 'id');
        $job_type = JobType::all()->pluck('name', 'id');
        $level_of_education = LevelOfEducation::all()->pluck('name', 'id');

        return view('pages.frontsite.home-page.index', compact('job_vacancy', 'province', 'job_type', 'level_of_education'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

app/Http/Controllers/Frontsite/Operational/ApplicantController.php
<?php

namespace App\Http\Controllers\Frontsite\Operational;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Operational\ApplyJobRequest;

use App\Models\Operational\Applicant;

use Illuminate\Http\Request;

class ApplicantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ApplyJobRequest $request)
    {
        $data = $request->all();

        $data['users_id'] = auth()->user()->id;

        $data['step'] = 1;

        Applicant::create($data);

        alert()->success('Pesan Sukses', 'Permohonan Anda telah dikirim');
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $my_application = Applicant::with(['job_vacancy.company.user', 'job_vacancy.position'])->findOrFail($id);

        return view('pages.frontsite.operational.application.show', compact('my_application'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }

    // custom function
    public function my_application()
    {
        $user = auth()->user();
        $my_application = Applicant::with(['job_vacancy.company.user', 'job_vacancy.position'])->latest()->where('users_id', $user->id)->paginate(500);

        return view('pages.frontsite.operational.application.index', compact('my_application'));
    }

    public function filter(Request $request, Applicant $applicant)
    {
        $data = $request->all();

        $user = auth()->user();

        // query builder 
        $applicant_query = $applicant->newQuery();

        if (isset($data['step'])) {
            $applicant_query->where('step', $data['step']);
        }

        $my_application = $applicant_query->with(['job_vacancy.company.user', 'job_vacancy.position'])
                                        ->latest()
                                        ->where('users_id', $user->id)
                                        ->paginate(500);


        return view('pages.frontsite.operational.application.index', compact('my_application'));
    }
}

app/Http/Controllers/Frontsite/Operational/CompanyController.php
<?php

namespace App\Http\Controllers\Frontsite\Operational;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Operational\StoreCompanyRequest;
use App\Http\Requests\Frontsite\Profile\StoreAccountRequest;

use App\Models\MasterData\Company;
use App\Models\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.frontsite.operational.company.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAccountRequest $request, StoreCompanyRequest $request_company)
    {
        $data_user = $request->all();

        // set user type
        $data_user['user_type_id'] = 2;

        // set hash password
        $data_user['password'] = Hash::make($data_user['password']);

        // create user
        $user = User::create($data_user);

        // sync role by users select
        $user->role()->sync(4);

        $data_company = $request_company->all();

        // set user id
        $data_company['users_id'] = $user->id;

        // set mobile phone
        if ($request->filled('contact')) {
            $data_company['contact'] = str_replace('+', '', $data_company['contact']);
            $data_company['contact'] = str_replace(' ', '', $data_company['contact']);
            $data_company['contact'] = str_replace('_', '', $data_company['contact']);
        }

        Company::create($data_company);

        return redirect()->back()->with('success', 'Silahkan cek email anda untuk update informasi akun anda.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }
}

resources/views/includes/frontsite/footer.blade.php
<!-- ========== FOOTER ========== -->
<footer class="bg-gold">
    <div class="container py-4 py-lg-6 text-center">
       <!-- Logo -->
      <a class="d-inline-flex align-items-center mb-3" href="{{ route('home') }}" aria-label="Front">
        <img class="w-100" style="max-width: 32rem" src="{{ asset('front-design/client-assets/images/penara-text-image.png') }}" alt="Logo">
      </a>
      <!-- End Logo -->

      <p class="text-white-50 fs-5 mb-1">Ruko Jewalk Jl. DR. Wahidin Sudirohusodo no 3 (Depan Kolam Renang Golf Jababeka)</p>
      <p class="text-white-50 fs-5 mb-5">Jatireja, Jababeka, Cikarang Timur, Kab. Bekasi.</p>

      <div class="border-top border-white-10 my-7"></div>

      <!-- Copyright -->
      <div class="w-100 text-lg-center mx-lg-auto">
        <p class="text-white-50 small">© Penara Job {{ date('Y') }}. All rights reserved.</p>
      </div>
      <!-- End Copyright -->
</footer>
<!-- ========== END FOOTER ========== -->

resources/views/includes/frontsite/go-to.blade.php
<!-- Go To -->
<a class="js-go-to go-to position-fixed" href="javascript:;" style="visibility: hidden;"
        data-hs-go-to-options='{
        "offsetTop": 200,
        "position": {
            "init": {
            "right": "2rem"
            },
            "show": {
            "bottom": "2rem"
            },
            "hide": {
            "bottom": "-2rem"
            }
        }
        }'>
    <i class="bi-chevron-up"></i>
</a>

resources/views/includes/frontsite/header.blade.php
<!-- ========== HEADER ========== -->
<header id="header" class="navbar navbar-expand-lg navbar-end navbar-light">

    <div class="container py-2">
      <nav class="js-mega-menu navbar-nav-wrap">
        <!-- Default Logo -->
        <a class="pe-3" href="{{ route('home') }}" aria-label="Front">
          <img class="" style="max-width: 100px; max-height: 90px" src="{{ asset('back-design/clients/img/logo.png') }}" alt="Logo">
        </a>
        <!-- End Default Logo -->

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-default">
            <i class="bi-list"></i>
          </span>
          <span class="navbar-toggler-toggled">
            <i class="bi-x"></i>
          </span>
        </button>
        <!-- End Toggler -->
      
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav justify-content-start">

            @guest
              <li class="nav-item">
                <a class="nav-link{{ request()->is('company') ? ' active' : '' }}" href="{{ route('company.index') }}">Perusahaan</a>
              </li>
            @endguest
          
            <li class="nav-item">
              <a class="nav-link{{ request()->is('announcement*') ? ' active' : '' }}" href="{{ route('announcement.index') }}">Pengumuman</a>
            </li>
          </ul>

          <ul class="navbar-nav justify-content-end mt-lg-1">
            @auth
              <li class="hs-has-sub-menu nav-item">
                <a id="companyMegaMenu" class="hs-mega-menu-invoker nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ Auth::user()->name ?? '' }}
                </a>

                <!-- Mega Menu -->
                <div class="hs-sub-menu dropdown-menu" aria-labelledby="companyMegaMenu" style="min-width: 14rem;">
                  <a class="dropdown-item" href="{{ route('profile.index') }}">Profile</a>
                  <a class="dropdown-item" href="{{ route('applicant.my_application') }}">Lamaran Saya</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item text-danger" href="{{ route('logout') }}"  onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    Logout
                  </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST"
                      style="display: none;">
                      @csrf
                  </form>
                </div>
                <!-- End Mega Menu -->
              </li>
            @else
              <li class="nav-item">
                <a class="btn btn-outline-gold d-grid d-lg-block mb-3 mb-lg-0" href="{{ route('login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="btn btn-gold btn-transition d-grid d-lg-block" href="{{ route('register') }}">Register</a>
              </li>
            @endauth
          </ul>
        </div>
        <!-- End Collapse -->
      </nav>
    </div>
</header>
<!-- ========== END HEADER ========== -->

resources/views/includes/frontsite/meta.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="The Pen4ra Jobs &amp; modern responsive website internal for management security.">
<meta name="keywords" content="pen4ra, jobs portal, jobs, management office, portal jobs">
<meta name="author" content="Artbycode">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

resources/views/includes/frontsite/script.blade.php
<!-- JS Global Compulsory  -->
<script src="{{ asset('front-design/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>

<!-- JS Implementing Plugins -->
<script src="{{ asset('front-design/assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/hs-show-animation/dist/hs-show-animation.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/hs-go-to/dist/hs-go-to.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/nouislider/dist/nouislider.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/fslightbox/index.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/tom-select/dist/js/tom-select.complete.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/hs-file-attach/dist/hs-file-attach.min.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/hs-toggle-password/dist/js/hs-toggle-password.js') }}"></script>
<script src="{{ asset('front-design/assets/vendor/imask/dist/imask.min.js') }}"></script>

<!-- JS Front -->
<script src="{{ asset('front-design/assets/js/theme.min.js') }}"></script>

{{-- inputmask --}}
<script src="{{ asset('front-design/assets/vendor/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('back-design/third-party/inputmask/dist/jquery.inputmask.js') }}"></script>
<script src="{{ asset('back-design/third-party/inputmask/dist/inputmask.js') }}"></script>

{{-- toastify  --}}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

<!-- JS Plugins Init. -->
<script>
    (function() {
        // INITIALIZATION OF MEGA MENU
        // =======================================================
        new HSMegaMenu('.js-mega-menu', {
            desktop: {
            position: 'left'
            }
        })


        // INITIALIZATION OF SHOW ANIMATIONS
        // =======================================================
        new HSShowAnimation('.js-animation-link')


        // INITIALIZATION OF BOOTSTRAP DROPDOWN
        // =======================================================
        HSBsDropdown.init()


        // INITIALIZATION OF INPUT MASK
        // =======================================================
        HSCore.components.HSMask.init('.js-input-mask')


        // INITIALIZATION OF TOGGLE PASSWORD
        // =======================================================
        new HSTogglePassword('.js-toggle-password')


        // INITIALIZATION OF FILE ATTACH
        // =======================================================
        new HSFileAttach('.js-file-attach')


        // INITIALIZATION OF SELECT
        // =======================================================
        var tomSelect = HSCore.components.HSTomSelect.init('.js-select')
        $('.js-select-clear').on('click', function (e) {
            e.preventDefault()
            tomSelect.clear()
        })


        // INITIALIZATION OF GO TO
        // =======================================================
        new HSGoTo('.js-go-to')


        // INITIALIZATION OF SWIPER
        // =======================================================
        var swiper = new Swiper('.js-swiper-employer-jobs',{
            slidesPerView: 1,
            navigation: {
            nextEl: '.js-swiper-employer-jobs-button-next',
            prevEl: '.js-swiper-employer-jobs-button-prev',
            },
            breakpoints: {
            480: {
                slidesPerView: 2,
                spaceBetween: 15,
            },
            768: {
                slidesPerView: 3,
                spaceBetween: 15,
            },
            }
        });


        // INITIALIZATION OF NOUISLIDER`
        // =======================================================
        HSCore.components.HSNoUISlider.init('.js-nouislider')
    })()
</script>

<script>
    // INITIALIZATION INPUTMASK
    // =======================================================
    $(":input").inputmask();
</script>

resources/views/includes/frontsite/style.blade.php
<!-- CSS Implementing Plugins -->
<link rel="stylesheet" href="{{ url('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css') }}">
<link rel="stylesheet" href="{{ url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css') }}">
<link rel="stylesheet" href="{{ asset('front-design/assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.css') }}">
<link rel="stylesheet" href="{{ asset('front-design/assets/vendor/nouislider/dist/nouislider.min.css') }}">
<link rel="stylesheet" href="{{ asset('front-design/assets/vendor/swiper/swiper-bundle.min.css') }}">
<link rel="stylesheet" href="{{ asset('front-design/assets/vendor/tom-select/dist/css/tom-select.bootstrap5.css') }}">

<!-- CSS Front Template -->
<link rel="stylesheet" href="{{ asset('front-design/assets/css/theme.min.css') }}">

{{-- toastify  --}}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

resources/views/includes/frontsite/toats-verify.blade.php
@if (Auth::check() && !Auth::user()->email_verified_at)
    <!-- Toast -->
    <div id="liveToast" class="d-none d-lg-block position-fixed toast text-white bg-danger show" role="alert" aria-live="assertive" aria-atomic="true" style="width: 500px; bottom: 20px; left: 30px; z-index: 1000;">
        <div class="toast-body d-flex align-items-center justify-content-between">
            <div>
                <div>
                    Your email : {{ Auth::user()->email }}
                </div>
                <div class="fs-5 mt-1">
                    Silahkan verifikasi email Anda.
                </div>
            </div>
            <div class="ml-auto">
                <form method="POST" action="{{ route('verification.send') }}">
                    @csrf
                    <button type="submit" class="btn btn-sm btn-outline-light" data-dismiss="toast" aria-label="Close">
                        <i class="bi bi-envelope me-1"></i> Kirim Ulang
                    </button>
                </form>
            </div>
        </div>
    </div>
    <!-- End Toast -->

    <!-- Toast -->
    <div id="liveToast" class="d-block d-lg-none position-fixed toast text-white bg-danger show start-50" role="alert" aria-live="assertive" aria-atomic="true" style="bottom: 0; transform: translate(-50%, -20%) !important; z-index: 1000;">
        <div class="toast-body d-flex align-items-center justify-content-between">
            <div>
                <div>
                    Your email : {{ Auth::user()->email }}
                </div>
                <div class="fs-5 mt-1">
                    Silahkan verifikasi email Anda.
                </div>
            </div>
            <div class="ml-auto">
                <form method="POST" action="{{ route('verification.send') }}">
                    @csrf
                    <button type="submit" class="btn btn-sm btn-outline-light" data-dismiss="toast" aria-label="Close">
                        <i class="bi bi-envelope"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <!-- End Toast -->
@endif

@push('after-script')    
    <script>
        @if (session('status') == 'verification-link-sent')
            Toastify({
                // icon check
                text: "Link verifikasi telah dikirim ke email Anda.",
                style: {
                background: "#00C9A7",
                color: "#ffffff",
                fontSize: "15px",
                textAlign: "center"
                },
                posisition: "top-center",
            }).showToast();
        @endif
    </script>
@endpush