routes/web.php
<?php

use App\Http\Controllers\Frontsite\HomeController;

use App\Http\Controllers\Frontsite\Profile\JobWishlistController;
use App\Http\Controllers\Frontsite\Profile\ProfilesController;
use App\Http\Controllers\Frontsite\Profile\UserExperienceController;
use App\Http\Controllers\Frontsite\Profile\UserEducationController;
use App\Http\Controllers\Frontsite\Profile\UserSkillController;
use App\Http\Controllers\Frontsite\Profile\UserResumeController;
use App\Http\Controllers\Frontsite\Profile\UserSecurityController;

use App\Http\Controllers\Frontsite\Operational\ApplicantController;
use App\Http\Controllers\Frontsite\Operational\CompanyController;
use App\Http\Controllers\Frontsite\Operational\JobVacancyController;

use App\Http\Controllers\Frontsite\Content\AnnouncementController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// frontsite ------------------------------- //

    // home ------------------------------- //
    Route::get('/', [HomeController::class, 'index'])->name('home');
    // end home ------------------------------- //
    
    
    // operational ------------------------------- //
        // job vacancy
        Route::get('job_vacancy/filter', [JobVacancyController::class, 'filter'])->name('job-vacancy.filter');
        Route::resource('job_vacancy', JobVacancyController::class);
        // company
        Route::resource('company', CompanyController::class);
    // end operational ------------------------------- //


    // content ------------------------------- //
        // announcement
        Route::resource('announcement', AnnouncementController::class);
    // end content ------------------------------- //
    

Route::group(['middleware' => ['auth:sanctum']], function () {
    
    // profile ------------------------------- //
        // personal info
        Route::get('select/regency/profile/{id}', [ProfilesController::class, 'select_regency_profile'])->name('select_regency.profile');
        Route::get('select/district/profile/{id}', [ProfilesController::class, 'select_district_profile'])->name('select_district.profile');
        Route::put('upload/photo/profile/{id}', [ProfilesController::class, 'upload'])->name('upload.photo.profile');
        Route::get('reset/photo/profile/{id}', [ProfilesController::class, 'reset'])->name('reset.photo.profile');
        Route::resource('profile', ProfilesController::class)->except('show');
        // Security
        Route::get('security/profile', [UserSecurityController::class, 'security'])->name('security.profile');
        Route::put('update/email/security/profile', [UserSecurityController::class, 'update_email'])->name('update.email.security.profile');
        Route::put('update/password/security/profile', [UserSecurityController::class, 'update_password'])->name('update.password.security.profile');
        Route::resource('security', UserSecurityController::class);
        // work experience
        Route::get('work_experience/profile', [UserExperienceController::class, 'work_experience'])->name('work_experience.profile');
        Route::resource('work_experience', UserExperienceController::class);
        // education
        Route::get('education/profile', [UserEducationController::class, 'education'])->name('education.profile');
        Route::resource('education', UserEducationController::class);
        // skill
        Route::get('reset/skill/profile', [UserSkillController::class, 'reset'])->name('reset.skill.profile');
        Route::get('skill/profile', [UserSkillController::class, 'skill'])->name('skill.profile');
        Route::resource('skill', UserSkillController::class);
        // resume
        Route::get('resume/profile', [UserResumeController::class, 'resume'])->name('resume.profile');
        Route::resource('resume', UserResumeController::class);
        // job wishlist
        Route::get('job_wishlist/profile', [JobWishlistController::class, 'wishlist'])->name('job_wishlist.profile');
        Route::resource('job_wishlist', JobWishlistController::class);
    // end profile ------------------------------- //


    // operational ------------------------------- //
        // my application
        Route::get('my_application/filter', [ApplicantController::class, 'filter'])->name('applicant.filter');
        Route::get('my_application', [ApplicantController::class, 'my_application'])->name('applicant.my_application');
        // apply job
        Route::resource('applicant', ApplicantController::class)->middleware('verified');
    // end operational ------------------------------- //

});
    
// end frontsite ------------------------------- //

app/Http/Controllers/Frontsite/Profile/JobWishlistController.php
<?php

namespace App\Http\Controllers\Frontsite\Profile;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Profile\AddJobWishlistRequest;

use App\Models\Operational\JobVacancyWishlist;

use Illuminate\Http\Request;

class JobWishlistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddJobWishlistRequest $request)
    {
        $data = $request->all();

        $user = auth()->user();

        $user->job_wishlist()->attach($data['job_vacancy_id']);

        alert()->success('Pesan Sukses', 'Lowongan kerja ditambahkan ke wishlist Anda');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // detach
        $user = auth()->user();

        $user->job_wishlist()->detach($id);

        alert()->success('Pesan Sukses', 'Lowongan kerja dihapus dari wishlist Anda');
        return redirect()->back();
    }

    // custom function
    public function wishlist()
    {
        $user = auth()->user();

        $job_wishlist = JobVacancyWishlist::with(['job_vacancy.company.user', 'job_vacancy.company.company_contract_history.company_contract', 'job_vacancy.position', 'job_vacancy.provinces'])
                                                ->latest()
                                                ->where('user_id', $user->id)
                                                ->paginate(10);

        return view('pages.frontsite.profile.job-wishlist.index', compact('job_wishlist'));
    }
}

app/Http/Controllers/Frontsite/Profile/ProfilesController.php
<?php

namespace App\Http\Controllers\Frontsite\Profile;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Profile\UpdateAccountRequest;
use App\Http\Requests\Frontsite\Profile\UpdateUserPersonalInformationRequest;
use App\Http\Requests\Frontsite\Profile\UploadPhotoProfileRequest;

use App\Models\ManagementAccess\UserPersonalInformation;
use App\Models\MasterData\Districts;
use App\Models\MasterData\Provinces;
use App\Models\MasterData\Regencies;
use App\Models\MasterData\Religion;
use App\Models\User;

use Illuminate\Http\Request;

use File;

class ProfilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();

        $province = Provinces::all()->pluck('name', 'id');
        $religion = Religion::all()->pluck('name', 'id');

        return view('pages.frontsite.profile.personal-info.index', compact('user','province', 'religion'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAccountRequest $request, UpdateUserPersonalInformationRequest $request_user_personal_information_request, $id)
    {
        // data
        $data = $request->all();

        $user = User::where('id', $id)->first();
        $user->update($data);

        $data = $request_user_personal_information_request->all();

        // set number id
        $data['number_id'] = str_replace(' ', '', $data['number_id']);
        $data['number_id'] = str_replace('_', '', $data['number_id']);

        // set mobile phone
        $data['contact_number'] = str_replace('+', '', $data['contact_number']);
        $data['contact_number'] = str_replace(' ', '', $data['contact_number']);
        $data['contact_number'] = str_replace('_', '', $data['contact_number']);

        // date of birth ------------------------------
        $date = $data['birth_date'];
        $d = substr($date, 0, 2);
        $m = substr($date, 3, 2);
        $y = substr($date, 6);
        $date = $y . '-' . $m . '-' . $d;
        $data['birth_date'] = $date; //change format
        // -----------------------------------------------

        $item = UserPersonalInformation::where('users_id', $user['id'])->first();
        $item->update($data);

        alert()->success('Success Message','Update data has been success');
        return redirect()->route('profile.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }

    // Custom Function
    public function upload(UploadPhotoProfileRequest $request, UserPersonalInformation $user_personal_information, $id)
    {
        // get current domain dan set to storage link
        $domain = $request->getSchemeAndHttpHost().'/storage'.'/';

        // first checking old photo to delete from storage
        $get_item = UserPersonalInformation::where('users_id', $id)->first();

        $position_string = strpos($get_item['photo'], 'assets');
        $get_item = substr($get_item['photo'], $position_string);

        $data = $get_item;
        $data = 'storage/'.$get_item;
        
        if (File::exists($data)) {
            File::delete($data);
        }else{
            $get_item = str_replace("storage/","", $data);
            File::delete('storage/app/public/'.$get_item);
        }
        
        // second get all request & set new path to request field path
        $data = $request->all();
        $data['photo'] = $request->file('photo')->store(
            'assets/photo-profile', 'public'
        );

        // concat current domain & path storage link file or photo
        $data['photo_url'] = $domain . $data['photo'];
        
        // third get first record as id user and update path
        $item = UserPersonalInformation::where('users_id', $id)->first();
        $item->update($data);

        alert()->success('Success Message','Upload photo has been success');
        return redirect()->route('profile.index');
    }

    public function reset(UserPersonalInformation $user_personal_information, $id)
    {
        // first checking old photo to delete from storage
        $get_item = UserPersonalInformation::where('users_id', $id)->first();
        $ids = $get_item['id'];

        $position_string = strpos($get_item['photo'], 'assets');
        $get_item = substr($get_item['photo'], $position_string);

        $data = 'storage/'.$get_item;
        if (File::exists($data)) {
            File::delete($data);
        }else{
            File::delete('storage/app/public/'.$get_item);
        }

        // second update value to null string
        $data = UserPersonalInformation::find($ids);
        $data->photo = null;
        $data->photo_url = null;
        $data->save();

        alert()->success('Success Message','Reset photo has been success');
        return redirect()->route('profile.index');

    }

    public function select_regency_profile($id)
    {
        // checking & validation
        $id = isset($id) ? $id : 0;

        // get data
        $regency['data'] = Regencies::where('province_id', $id)->orderBy('name', 'asc')->get();

        return response()->json($regency);

    }

    public function select_district_profile($id)
    {
        // checking & validation
        $id = isset($id) ? $id : 0;

        // get data
        $district['data'] = Districts::where('regency_id', $id)->orderBy('name', 'asc')->get();

        return response()->json($district);
    }
}

app/Http/Controllers/Frontsite/Profile/UserSecurityController.php
<?php

namespace App\Http\Controllers\Frontsite\Profile;

use App\Http\Controllers\Controller;

use App\Http\Requests\Frontsite\Profile\UpdateUserSecurityEmailRequest;
use App\Http\Requests\Frontsite\Profile\UpdateUserSecurityPasswordRequest;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserSecurityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return abort(404);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return abort(404);
    }

     // custom function
    public function security()
    {
        $user = auth()->user();

        return view('pages.frontsite.profile.security.index', compact('user'));
    }

    public function update_email(UpdateUserSecurityEmailRequest $request)
    {
        $data = $request->all();

        $user = auth()->user();

         // generates a token and sends a verification mail
        if ($user->email != $data['email']) {
            $user->newEmail($data['email']);
        }

        alert()->success('Success Message', 'Update email has been success');
        return redirect()->route('security.profile');
    }

    public function update_password(UpdateUserSecurityPasswordRequest $request)
    {
        $data = $request->all();

        $user = auth()->user();

        // sets the new password
        $data['password'] = Hash::make($data['password']);

        // updates
        $user->update($data);

        alert()->success('Success Message', 'Update password has been success');
        return redirect()->route('security.profile');
    }
}

resources/views/pages/frontsite/profile/skill/index.blade.php
@extends('layouts.default')

{{-- set section --}}
@section('title', 'Keahlian - Profile | Penara')

@section('content')
    <main id="content" role="main" class="">
        <!-- Breadcrumb -->
        <div class="navbar-dark bg-gold" style="background-image: url({{ asset('front-design/assets/svg/components/wave-pattern-light.svg') }});">
            <div class="container content-space-1 content-space-b-lg-3">
                <div class="row align-items-center">
                    <div class="col">
                        <div class="d-none d-lg-block">
                            <h1 class="h2 text-white">Keahlian</h1>
                        </div>

                        <!-- Breadcrumb -->
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb breadcrumb-light mb-0">
                                <li class="breadcrumb-item">Akun</li>
                                <li class="breadcrumb-item active" aria-current="page">Keahlian</li>
                            </ol>
                        </nav>
                        <!-- End Breadcrumb -->
                    </div>
                    <!-- End Col -->

                    <div class="col-auto">
                        <div class="d-none d-lg-block">
                            <a class="btn btn-soft-light btn-sm" href="{{ route('home') }}">Back to home</a>
                        </div>

                        <!-- Responsive Toggle Button -->
                        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarNav" aria-controls="sidebarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-default">
                                <i class="bi-list"></i>
                            </span>
                            <span class="navbar-toggler-toggled">
                                <i class="bi-x"></i>
                            </span>
                        </button>
                        <!-- End Responsive Toggle Button -->
                    </div>
                    <!-- End Col -->
                </div>
                <!-- End Row -->
            </div>
        </div>
        <!-- End Breadcrumb -->

        <!-- Content -->
        <div class="container content-space-t-1 content-space-b-3 content-space-b-md-5 content-space-t-lg-0 content-space-b-lg-2 mt-lg-n10">
            <div class="row">
                <div class="col-lg-3">
                    
                    @include('includes.profile.menu')

                </div>
                <!-- End Col -->

                <div class="col-lg-9">
                    <!-- Card -->
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h5 class="card-title">Keahlian</h5>

                            <!-- Error -->
                            @if ($errors->any())
                                <div class="alert alert-soft-danger alert-dismissible fade show mt-4" role="alert">
                                    <div class="fw-semi-bold">{{ __('Ups! Ada yang salah.') }}</div>
                                    <ul class="mt-3 mb-0">
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            @endif
                            <!-- End Error -->
                        </div>

                        <!-- Body -->
                        <div class="card-body">
                            <!-- Form -->
                            <form action="{{ route('skill.store') }}" method="POST">

                                @csrf

                                <!-- Form -->
                                <div class="row mb-4">
                                    <label for="skill" class="col-sm-3 col-form-label form-label">Keahlian</label>

                                    <div class="col-sm-9">
                                        <!-- Select -->
                                        <div class="tom-select-custom">
                                            <select class="js-select form-select" name="skill[]" multiple id="skill" autocomplete="off"
                                                data-hs-tom-select-options='{
                                                    "placeholder": "Pilih Keahlian..."
                                                }'>
                                                    <option value="">Pilih Keahlian...</option>
                                                    @forelse ($skill as $id => $skill_item_name)
                                                        <option value="{{ $id }}" {{ (in_array($id, old('skill', isset($user) ? $user->skill->pluck('id')->toArray() : ''))) ? 'selected' : '' }}>{{ $skill_item_name }}</option>
                                                    @empty
                                                        <option value="">Tidak ada data</option>
                                                    @endforelse
                                            </select>
                                        </div>
                                        <!-- End Select -->
                                    </div>
                                </div>
                                <!-- End Form -->

                                
                                <div class="d-grid d-md-flex justify-content-md-end gap-3 mt-3">
                                    <a class="btn btn-white order-3 order-md-1" href="{{ route('skill.profile') }}" onclick="return confirm('Anda yakin ingin menutup halaman ini? , Setiap perubahan yang Anda buat tidak akan disimpan.')">
                                        Batal
                                    </a>
                                    @if ($user->skill->count() > 0)
                                        <a href="{{ route('reset.skill.profile') }}" class="btn btn-soft-secondary order-2 order-md-2" onclick="return confirm('Apakah Anda yakin ingin mereset keahlian Anda?')">
                                            Reset
                                        </a>
                                    @endif
                                    <button type="submit" class="btn btn-gold order-1 order-md-3" onclick="return confirm('Apakah Anda yakin ingin menyimpan data ini?')">Simpan</button>
                                </div>
                            </form>
                            <!-- End Form -->
                        </div>
                        <!-- End Body -->
                    </div>
                    <!-- End Card -->
                </div>
                <!-- End Col -->
            </div>
        </div>
    </main>
            
@endsection

@push('after-style')
    <link rel="stylesheet" href="{{ asset('/back-design/third-party/datetimepicker/css/bootstrap-datetimepicker.min.css') }}">
@endpush


@push('after-script')
    <script src="{{ url('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js') }}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="{{ url('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js') }}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{{ url('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js') }}" type="text/javascript"></script>

    <script src="{{ asset('/back-design/third-party/datetimepicker/js/bootstrap-datetimepicker.min.js') }}"></script>

    <script>
          $('#end_date').datetimepicker({
              format: 'DD/MM/YYYY'
          });
    </script> 

@endpush